- TestWeb/.angulardoc.json
- TestWeb/.vscode/launch.json
- TestWeb/.vscode/tasks.json
- TestWeb/ClientApp/src/app/create-hearing/create-hearing.component.html
https://tools.hmcts.net/jira/browse/VIH-6627
- initial working project with MS Login
```
[ ] Yes
[X] No
```
> VIH-6627 Initial working project

- TestWeb.AcceptanceTests/Hooks/ConfigHooks.cs
- azure-pipelines.release.yml
- azure-pipelines.yml
- Get initial pipeline working
```
[ ] Yes
[X] No
```
> VIH-6690 Fix pipelines

- azure-pipelines.nightly.yml
https://tools.hmcts.net/jira/browse/VIH-6949
- Create overnight pipeline
```
[ ] Yes
[X] No
```
> VIH-6949 Create overnight pipeline

- TestWeb.AcceptanceTests/Features/AllocateUsers.feature
- TestWeb.AcceptanceTests/Hooks/DriverHooks.cs
- TestWeb.AcceptanceTests/Pages/AllocateUsersPage.cs
- TestWeb.AcceptanceTests/Steps/AllocateUsersSteps.cs
- TestWeb/ClientApp/jasmine-tests/TESTS.xml
- TestWeb/ClientApp/package-lock.json
- TestWeb/ClientApp/package.json
- TestWeb/ClientApp/src/app/allocate-users/allocate-users/allocate-users.component.html
- TestWeb/ClientApp/src/app/allocate-users/allocate-users/allocate-users.component.ts
- TestWeb/ClientApp/src/app/services/test-api/allocation-service.ts
- TestWeb/ClientApp/src/app/services/test-api/test-api-service.spec.ts
- TestWeb/ClientApp/src/app/services/test-api/test-api-service.ts
- azure-pipelines.nightly.yml
https://tools.hmcts.net/jira/browse/VIH-6976
- Added unallocated all button to Allocations Page
```
[ ] Yes
[X] No
```
> VIH-6976 Added unallocate all button to Allocations Page

- TestWeb/ClientApp/jasmine-tests/TESTS.xml
- TestWeb/ClientApp/src/app/allocate-users/allocate-users/allocate-users.component.spec.ts
- TestWeb/ClientApp/src/app/allocate-users/allocate-users/allocate-users.component.ts
- TestWeb/ClientApp/src/app/events/events.component.spec.ts
- TestWeb/ClientApp/src/app/events/events.component.ts
- TestWeb/ClientApp/src/app/hearings/delete-hearing/delete-hearing.component.spec.ts
- TestWeb/ClientApp/src/app/services/test-api/allocation-service.spec.ts
- TestWeb/ClientApp/src/app/services/test-api/create-service.ts
- TestWeb/ClientApp/src/app/services/test-api/models/summary.spec.ts
- TestWeb/ClientApp/src/app/services/test-api/reset-service.spec.ts
- TestWeb/ClientApp/src/app/services/test-api/reset-service.ts
- TestWeb/ClientApp/src/app/services/test-api/test-api-service.spec.ts
- TestWeb/ClientApp/src/app/shared/header/header.component.spec.ts
- TestWeb/ClientApp/src/app/testing/mocks/testapiservice-test-data.ts
- azure-pipelines.nightly.yml
https://tools.hmcts.net/jira/browse/VIH-6971
- Added more code coverage
- Added potential fix for overnight tests
```
[ ] Yes
[X] No
```
> VIH-6671 Added more Jasmine test code coverage

- TestWeb.AcceptanceTests/Features/AllocateUsers.feature
- TestWeb.AcceptanceTests/Features/CreateHearings.feature
- TestWeb.AcceptanceTests/Features/Login.feature
- TestWeb.AcceptanceTests/Hooks/DriverHooks.cs
- TestWeb.AcceptanceTests/Hooks/HooksSequence.cs
- TestWeb.AcceptanceTests/Steps/AllocateUsersSteps.cs
- TestWeb.AcceptanceTests/Steps/BrowserSteps.cs
- TestWeb.AcceptanceTests/Steps/SummarySteps.cs
- TestWeb.TestApi.Client/TestApiClient.cs
- TestWeb/ClientApp/package-lock.json
- TestWeb/ClientApp/package.json
https://tools.hmcts.net/jira/browse/VIH-7059
- Refactoring the driver hooks for local parallel test execution
- Refactor some AC scenarios
```
[ ] Yes
[X] No
```
> VIH-7059 refactor hooks and tests

- TestWeb/ClientApp/src/app/hearings/create-hearing/create-hearing.component.html
https://tools.hmcts.net/jira/browse/VIH-6948
- updated label for Skip Service Web
```
[ ] Yes
[X] No
```
> VIH-6948 Update label for Skip Service Web

- TestWeb.AcceptanceTests/TestWeb.AcceptanceTests.csproj
- TestWeb.AcceptanceTests/packages.lock.json
- TestWeb.AcceptanceTests/parameters.runsettings
- Added Windows env switching
```
[ ] Yes
[X] No
```
> VIH-7058 Added Windows env switching

- TestWeb.AcceptanceTests/packages.lock.json
- TestWeb.IntegrationTests/packages.lock.json
- TestWeb.TestApi.Client/TestApiClient.cs
- TestWeb.Tests.Common/Builders/Requests/ConfirmHearingBuilder.cs
- TestWeb.Tests.Common/Builders/Responses/BookingsHearingResponseBuilder.cs
- TestWeb.Tests.Common/Builders/Responses/HearingsResponseBuilder.cs
- TestWeb.UnitTests/packages.lock.json
- TestWeb/Program.cs
- TestWeb/TestWeb.csproj
- TestWeb/packages.lock.json
VIH-7176
Add new configuration provider for SDS
```
[ ] Yes
[x] No
```
> VIH-7176 Add new configuration provider for SDS

- TestWeb/Program.cs
VIH-7176
Also load config values from vh-infra-core folder
```
[ ] Yes
[x] No
```
> VIH-7176 Also load config values from vh-infra-core folder

- TestWeb/TestWeb.AcceptanceTests/Steps/BrowserSteps.cs
- TestWeb/TestWeb.TestApi.Client/TestApiClient.cs
- TestWeb/TestWeb/ClientApp/package-lock.json
https://tools.hmcts.net/jira/browse/VIH-7059
- remove parallel execution workaround
```
[ ] Yes
[X] No
```
> VIH-7059 Remove Parallel Execution Workaround

- TestWeb/TestWeb/ClientApp/src/app/allocate-users/allocate-users/allocate-users.component.html
- TestWeb/TestWeb/ClientApp/src/app/home/home.component.html
- Changed column name
```
[ ] Yes
[X] No
```
> VIH-5552 Changed column name

- TestWeb/TestWeb.AcceptanceTests/Pages/HomePage.cs
https://tools.hmcts.net/jira/browse/VIH-5552
- update to locators for new usernames
```
[ ] Yes
[X] No
```
> VIH-5552 Update locators for new usernames

- TestWeb/TestWeb.TestApi.Client/TestApiClient.cs
- TestWeb/TestWeb/ClientApp/src/app/allocate-users/allocate-users/allocate-users.component.ts
- TestWeb/TestWeb/ClientApp/src/app/hearings/create-hearing/create-hearing.component.html
- TestWeb/TestWeb/ClientApp/src/app/hearings/create-hearing/create-hearing.component.ts
- TestWeb/TestWeb/ClientApp/src/app/security/unauthorised/unauthorised.component.html
- TestWeb/TestWeb/ClientApp/src/app/services/clients/api-client.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/allocation-service.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/allocation-service.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/hearing-service.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/models/hearing-form-data.ts
- TestWeb/TestWeb/ClientApp/src/app/shared/error/error.component.html
- TestWeb/TestWeb/ClientApp/src/app/testing/mocks/testapiservice-test-data.ts
https://tools.hmcts.net/jira/browse/VIH-7345
- Add witnesses
- 
```
[ ] Yes
[X] No
```
> VIH-7345 Add witnesses

- TestWeb/TestWeb.AcceptanceTests/Data/DefaultData.cs
- TestWeb/TestWeb.AcceptanceTests/Pages/CreateHearingPage.cs
- TestWeb/TestWeb.AcceptanceTests/Steps/CreateHearingsSteps.cs
- TestWeb/TestWeb.TestApi.Client/TestApiClient.cs
- TestWeb/TestWeb/ClientApp/src/app/allocate-users/allocate-users/allocate-users.component.ts
- TestWeb/TestWeb/ClientApp/src/app/hearings/create-hearing/create-hearing.component.html
- TestWeb/TestWeb/ClientApp/src/app/hearings/create-hearing/create-hearing.component.ts
- TestWeb/TestWeb/ClientApp/src/app/services/clients/api-client.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/allocation-service.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/allocation-service.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/hearing-service.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/models/hearing-form-data.ts
- TestWeb/TestWeb/ClientApp/src/app/testing/mocks/testapiservice-test-data.ts
https://tools.hmcts.net/jira/browse/VIH-7347
- Added interpreters
```
[ ] Yes
[X] No
```
> VIH-7347 Add interpreters

- TestWeb/TestWeb/ClientApp/src/app/services/api/config.service.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/confirm-service.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/create-service.spec.ts
https://tools.hmcts.net/jira/browse/VIH-7351
- Improve Jasmine Coverage
```
[ ] Yes
[X] No
```
> VIH-7351 Improve Jasmine Coverage

- TestWeb/TestWeb.AcceptanceTests/Features/CreateHearings.feature
- TestWeb/TestWeb.AcceptanceTests/Pages/CreateHearingPage.cs
- TestWeb/TestWeb.AcceptanceTests/Steps/CreateHearingsSteps.cs
- TestWeb/TestWeb.TestApi.Client/TestApiClient.cs
- TestWeb/TestWeb/ClientApp/src/app/hearings/create-hearing/create-hearing.component.html
- TestWeb/TestWeb/ClientApp/src/app/hearings/create-hearing/create-hearing.component.ts
- TestWeb/TestWeb/ClientApp/src/app/services/clients/api-client.ts
- Prevent interpreters not having an individual to be linked with
```
[ ] Yes
[X] No
```
> VIH-5552 Added tests and error messages

- TestWeb/TestWeb.AcceptanceTests/Steps/CreateHearingsSteps.cs
- TestWeb/TestWeb.AcceptanceTests/Steps/LoginSteps.cs
- Fix for timezone errors
```
[ ] Yes
[X] No
```
> VIH-5552 Fix for timezone error

- TestWeb/TestWeb.AcceptanceTests/Helpers/DateFormats.cs
- TestWeb/TestWeb.AcceptanceTests/Steps/CreateHearingsSteps.cs
- Fix for SauceLabs Timezone
```
[ ] Yes
[X] No
```
> VIH-5552 Fix for SauceLabs Timezone

- TestWeb/TestWeb/ClientApp/src/app/common/models/event-model.ts
- TestWeb/TestWeb/ClientApp/src/app/events/events.component.html
- TestWeb/TestWeb/ClientApp/src/app/events/events.component.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/events/events.component.ts
- TestWeb/TestWeb/ClientApp/src/app/services/api/mappers/map-event.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/services/api/mappers/map-event.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/event-service.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/event-service.ts
- Added a participant room id textfield
```
[ ] Yes
[X] No
```
> VIH-5552 Added a participant room id textfield

- TestWeb/TestWeb.AcceptanceTests/packages.lock.json
- TestWeb/TestWeb.Contracts/TestWeb.Contracts.csproj
- TestWeb/TestWeb.IntegrationTests/packages.lock.json
- TestWeb/TestWeb.Tests.Common/TestWeb.Tests.Common.csproj
- TestWeb/TestWeb.UnitTests/packages.lock.json
- TestWeb/TestWeb/ClientApp/src/app/allocate-users/allocate-users/allocate-users.component.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/events/events.component.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/hearings/create-hearing/create-hearing.component.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/hearings/summary/summary.component.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/home/home.component.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/allocation-service.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/conference-service.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/confirm-service.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/create-service.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/hearing-service.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/models/summary.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/summaries-service.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/services/test-api/test-api-service.spec.ts
- TestWeb/TestWeb/ClientApp/src/app/testing/mocks/test-data.ts
- TestWeb/TestWeb/TestWeb.csproj
- TestWeb/TestWeb/packages.lock.json
- Fixed code smells
- Upgraded to stable NuGet version
```
[ ] Yes
[X] No
```
> VIH-5552 Fixed code smells

- TestWeb/TestWeb.AcceptanceTests/TestWeb.AcceptanceTests.csproj
- TestWeb/TestWeb.AcceptanceTests/packages.lock.json
- TestWeb/TestWeb.IntegrationTests/TestWeb.IntegrationTests.csproj
- TestWeb/TestWeb.IntegrationTests/packages.lock.json
- TestWeb/TestWeb.Tests.Common/TestWeb.Tests.Common.csproj
- TestWeb/TestWeb.UnitTests/TestWeb.UnitTests.csproj
- TestWeb/TestWeb.UnitTests/packages.lock.json
- update to AC NuGet
```
[ ] Yes
[X] No
```
> VIH-5552 Upgrade to new AC NuGet

- TestWeb/TestWeb.AcceptanceTests/Steps/AllocateUsersSteps.cs
- TestWeb/TestWeb.AcceptanceTests/Steps/EventsSteps.cs
- TestWeb/TestWeb.AcceptanceTests/Steps/HomeSteps.cs
- TestWeb/TestWeb.AcceptanceTests/Steps/SummarySteps.cs
- TestWeb/TestWeb.AcceptanceTests/TestWeb.AcceptanceTests.csproj
- TestWeb/TestWeb.AcceptanceTests/packages.lock.json
- TestWeb/TestWeb.IntegrationTests/TestWeb.IntegrationTests.csproj
- TestWeb/TestWeb.IntegrationTests/packages.lock.json
- TestWeb/TestWeb.Tests.Common/TestWeb.Tests.Common.csproj
- TestWeb/TestWeb.UnitTests/TestWeb.UnitTests.csproj
- TestWeb/TestWeb.UnitTests/packages.lock.json
- Update to AC package
- update get text to use TextOf
```
[ ] Yes
[X] No
```
> VIH-5552 Update to use TextOf

- TestWeb/TestWeb.AcceptanceTests/Hooks/ConfigHooks.cs
- TestWeb/TestWeb.Common/Configuration/HearingServicesConfiguration.cs
- TestWeb/TestWeb.Common/Security/AppRoles.cs
- TestWeb/TestWeb.UnitTests/.config/dotnet-tools.json
- TestWeb/TestWeb.UnitTests/Mappings/UserProfileResponseMapperTests.cs
- TestWeb/TestWeb.UnitTests/stryker-config.json
- TestWeb/TestWeb/Mappings/UserProfileResponseMapper.cs
- azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-7050
- Added mutation testing to Test Web
```
[ ] Yes
[X] No
```
> VIH-7050 Added mutation testing to Test Web

- TestWeb/TestWeb/web.config
https://tools.hmcts.net/jira/browse/VIH-7135
Remove HTTP Headers
```
[ ] Yes
[x] No
```
> VIH-7135 Verbose-HTTP-Headers Web.Config

- azure-pipelines.nightly.yml
- azure-pipelines.release.yml
- azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-7660
Updated PAT for AZDO
```
[ ] Yes
[X] No
```
> VIH-7660 - updated PAT

- azure-pipelines.nightly.yml
N/A
Changed the start time to midnight to rule out any interference from other runs
```
[ ] Yes
[X] No
```
> changed run time to 23:00

- TestWeb/TestWeb.AcceptanceTests/TestWeb.AcceptanceTests.csproj
- TestWeb/TestWeb.AcceptanceTests/packages.lock.json
- TestWeb/TestWeb.Common/TestWeb.Common.csproj
- TestWeb/TestWeb.Contracts/TestWeb.Contracts.csproj
- TestWeb/TestWeb.IntegrationTests/TestWeb.IntegrationTests.csproj
- TestWeb/TestWeb.IntegrationTests/packages.lock.json
- TestWeb/TestWeb.Tests.Common/TestWeb.Tests.Common.csproj
- TestWeb/TestWeb.UnitTests/TestWeb.UnitTests.csproj
- TestWeb/TestWeb.UnitTests/packages.lock.json
- TestWeb/TestWeb.sln
- TestWeb/TestWeb/TestWeb.csproj
- TestWeb/TestWeb/packages.lock.json
- azure-pipelines.yml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> VIH-8595 - fix dependencies

- TestWeb/TestWeb.AcceptanceTests/TestWeb.AcceptanceTests.csproj
- TestWeb/TestWeb.AcceptanceTests/packages.lock.json
- TestWeb/TestWeb.IntegrationTests/TestWeb.IntegrationTests.csproj
- TestWeb/TestWeb.IntegrationTests/packages.lock.json
- TestWeb/TestWeb.Tests.Common/TestWeb.Tests.Common.csproj
- TestWeb/TestWeb.UnitTests/TestWeb.UnitTests.csproj
- TestWeb/TestWeb.UnitTests/packages.lock.json
- TestWeb/TestWeb/ClientApp/package-lock.json
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> VIH-7009 - Update dependency on VH-AcceptanceTests due to ChromeDriver update

- TestWeb/TestWeb/Program.cs
- azure-pipelines.sds.pr-release.yml
- charts/vh-test-web/Chart.yaml
- charts/vh-test-web/values.demo.template.yaml
- charts/vh-test-web/values.dev.template.yaml
- charts/vh-test-web/values.yaml
VIH-9239 - update test web app settings
```
[ ] Yes
[ x ] No
```
> VIH-9239 - update test web app settings

- TestWeb/TestWeb/Dockerfile
https://tools.hmcts.net/jira/browse/VIH-9477
VIH-9477 Add curl to docker build
```
[ ] Yes
[X] No
```
> VIH-9477 Add curl to docker build

- azure-pipelines.sds.master-release.yml
- azure-pipelines.sds.pr-close.yml
- azure-pipelines.sds.pr-release.yml
- azure-pipelines.sds.release.yml
VIH-9517 - Add master release pipeline
VIH-9517 - Add master release pipeline
```
[ ] Yes
[ x ] No
```
> VIH-9517 - Add master release pipeline
